### ISSUE TITLE
Is the agent still working ?

### ISSUE THREAD

**Issue by nicolas-graves** [aleb/git-lfs-rsync-agent#3]
I can't get the program to work properly. I don't even get error messages or any text. Even when replacing the only quoted "rsync" in the program by "echo", there's nothing happening. 

If it is still working, it lacks documentation. 
Some things that would be better if pointed out:
- lfsconfig has to be changed in the README . the commands in README add configuration in .git/config.

**Comment by nicolas-graves** [comment]
By the way if use @nathasm fork (because it's the one packaged), but I write here because he/she doesn't have an issue section.

**Comment by aleb** [comment]
I don't use it anymore.

**Comment by nicolas-graves** [comment]
Good to know. Can you put a warning on top of the README to notify that ? Thanks !
